"use client";

import clsx from "clsx";

type Brand = "BGP" | "AIMO";

// ─── BGP wrapper ─────────────────────────────────────────────────────────────

const BGP_LOGO_URL = 'https://email-editor-production.s3.amazonaws.com/images/665130/Logo_BGP_16%20(2).png';
const BGP_WHATSAPP_LINK = 'https://wa.me/5551992091726?text=Ol%C3%A1%2C%20quero%20falar%20sobre%20o%20meu%20financeiro!';
const BGP_FONT = "Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif";

const AIMO_LOGO_URL = '/aimo-logo.png';
const AIMO_FONT = "'Space Grotesk','Inter','Helvetica Neue',Arial,sans-serif";
const AIMO_PRIMARY = '#1E3FFF';

/**
 * Strips html/head/body tags and (when present) the outer layout tables
 * generated by compileFullHtml() so we extract just the inner body content.
 */
function stripToInnerBody(bodyHtml: string): string {
  const clean = bodyHtml
    .replace(/<!DOCTYPE[^>]*>/gi, '')
    .replace(/<\/?html[^>]*>/gi, '')
    .replace(/<head[\s\S]*?<\/head>/gi, '')
    .replace(/<\/?body[^>]*>/gi, '');

  const outerTableRe =
    /^\s*<table[^>]*>\s*<tr>\s*<td[^>]*align=["']center["'][^>]*>\s*<table[^>]*>\s*<tr>\s*<td[^>]*>([\s\S]*)<\/td>\s*<\/tr>\s*<\/table>\s*<\/td>\s*<\/tr>\s*<\/table>\s*$/i;
  const match = clean.trim().match(outerTableRe);
  return match ? match[1] : clean;
}

/**
 * BGP brand preview — exact mirror of backend wrapBgpTemplate().
 */
export function wrapBgpPreview(bodyHtml: string): string {
  const content = stripToInnerBody(bodyHtml);

  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background-color:#f4f4f4;font-family:${BGP_FONT};-webkit-font-smoothing:antialiased;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;">
<tbody><tr><td align="center">

<!-- HEADER: Logo -->
<table align="center" cellpadding="0" cellspacing="0" role="presentation" style="width:605px;margin:0 auto">
<tbody><tr><td style="padding-top:48px;padding-bottom:24px;text-align:center">
<a href="https://bertuzzipatrimonial.com.br" target="_blank"><img src="${BGP_LOGO_URL}" style="display:inline-block;height:auto;border:0;width:206px" alt="BGP"></a>
</td></tr></tbody></table>

<!-- BODY: White card -->
<table align="center" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#fff;border-radius:16px 16px 0 0;width:605px;margin:0 auto">
<tbody><tr><td style="padding:48px 60px 32px;font-family:${BGP_FONT};font-size:16px;font-weight:400;line-height:1.5;color:#000;">
${content}
</td></tr></tbody></table>

<!-- SPACER -->
<table align="center" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#fff;width:605px;margin:0 auto">
<tbody><tr><td style="height:16px;line-height:16px;font-size:1px">&nbsp;</td></tr></tbody></table>

<!-- SOCIAL ICONS -->
<table align="center" cellpadding="0" cellspacing="0" role="presentation" style="width:605px;margin:0 auto">
<tbody><tr><td style="padding:10px;text-align:center">
<a href="https://www.instagram.com/bertuzzigp/" target="_blank" style="display:inline-block;margin:0 10px"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-color/instagram@2x.png" width="32" height="auto" alt="Instagram" style="display:block;border:0"></a>
<a href="https://www.youtube.com/@bertuzzigp" target="_blank" style="display:inline-block;margin:0 10px"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-color/youtube@2x.png" width="32" height="auto" alt="YouTube" style="display:block;border:0"></a>
<a href="${BGP_WHATSAPP_LINK}" target="_blank" style="display:inline-block;margin:0 10px"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-color/whatsapp@2x.png" width="32" height="auto" alt="WhatsApp" style="display:block;border:0"></a>
</td></tr></tbody></table>

<!-- FOOTER -->
<table align="center" cellpadding="0" cellspacing="0" role="presentation" style="width:605px;margin:0 auto">
<tbody><tr><td style="padding:0 10px 24px">
<p style="font-family:${BGP_FONT};font-size:10px;color:#8c8c8c;line-height:1.5;text-align:center;margin:0;">
Enviado por www.bertuzzipatrimonial.com.br<br>
Av. Carlos Gomes, 75 - Sala 603 - Auxiliadora, Porto Alegre - RS, 90480-000<br>
Caso não queira mais receber estes e-mails, <span style="text-decoration:underline">cancele sua inscrição</span>.
</p>
</td></tr></tbody></table>

</td></tr></tbody></table>
</body>
</html>`;
}

/**
 * AIMO brand preview — pass-through inteligente.
 * Se o html é doc completo (template AIMO self-contained), retorna intacto.
 * Senão, aplica wrap institucional AIMO com header (logo) + footer dark.
 */
export function wrapAimoPreview(bodyHtml: string): string {
  // Detecta se já é doc HTML completo (template AIMO self-contained)
  const isCompleteDoc = /<!DOCTYPE|<html[\s>]/i.test(bodyHtml.trim().slice(0, 200));
  if (isCompleteDoc) {
    return bodyHtml; // pass-through — respeita template completo
  }

  // Snippet (IA, edição livre, etc) — wrap institucional AIMO
  // (mirror exato do wrapAimoTemplate backend).
  const content = stripToInnerBody(bodyHtml);
  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap');
body { margin:0; padding:0; background-color:#F4F5F8; font-family:'Inter','Space Grotesk',system-ui,Arial,sans-serif; color:#0A0E1F; }
a { color:#1E3FFF; }
</style>
</head>
<body>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#F4F5F8;">
<tr><td align="center" style="padding:32px 16px;">

<!-- Container principal 600px -->
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#FFFFFF;border-radius:12px;overflow:hidden;">

<!-- Header com logo AIMO -->
<tr>
<td align="left" style="padding:32px 40px 24px 40px;background-color:#FFFFFF;border-bottom:1px solid #E6E8EF;">
<img src="/aimo-logo.png" alt="AiMO" width="96" style="display:block;width:96px;height:auto;border:0;" />
</td>
</tr>

<!-- Body -->
<tr>
<td style="padding:40px;font-family:'Inter','Space Grotesk',system-ui,Arial,sans-serif;font-size:15px;line-height:1.65;color:#0A0E1F;">
${content}
</td>
</tr>

<!-- Footer institucional AiMO (dark) -->
<tr>
<td style="padding:32px 40px 32px 40px;background-color:#0A0E1F;border-top:1px solid #1A2040;">
<table role="presentation" border="0" cellpadding="0" cellspacing="0">
<tr>
<td valign="middle" style="padding-right:12px;">
<img src="/aimo-logo.png" alt="AiMO" width="56" style="display:block;width:56px;height:auto;border:0;filter:brightness(0) invert(1);" />
</td>
<td valign="middle">
<span style="font-family:'Space Grotesk','Inter',system-ui,sans-serif;font-size:13px;font-weight:500;color:#FFFFFF;letter-spacing:0.02em;">AiMO Corp</span>
</td>
</tr>
</table>
<p style="margin:18px 0 0 0;font-family:'Inter','Space Grotesk',system-ui,sans-serif;font-size:12px;line-height:1.6;color:#6B7390;">
Gestão patrimonial inteligente.<br />
aimocorp.com.br
</p>
<div style="width:100%;height:1px;background-color:#1A2040;margin:20px 0;font-size:0;line-height:0;">&nbsp;</div>
<p style="margin:0;font-family:'Inter','Space Grotesk',system-ui,sans-serif;font-size:11px;line-height:1.6;color:#6B7390;">
Você está recebendo este email porque demonstrou interesse em conteúdos da AiMO.
</p>
</td>
</tr>

</table>

</td></tr></table>
</body>
</html>`;
}

/**
 * Brand-aware dispatcher. Default BGP for backward compat.
 */
export function wrapInBrandPreview(bodyHtml: string, brand: Brand = "BGP"): string {
  if (brand === "AIMO") return wrapAimoPreview(bodyHtml);
  return wrapBgpPreview(bodyHtml);
}

interface EmailPreviewProps {
  html: string;
  className?: string;
  /** When true, wraps the html in the brand template before rendering */
  branded?: boolean;
  /** Which brand wrapper to use (only relevant if branded is true). Default BGP. */
  brand?: Brand;
}

// Script injected into preview iframe to open all links in a new tab
const LINK_INTERCEPT_SCRIPT = `<script>
document.addEventListener('click', function(e) {
  var a = e.target.closest('a');
  if (a && a.href) {
    e.preventDefault();
    window.open(a.href, '_blank', 'noopener');
  }
});
</script>`;

export default function EmailPreview({ html, className, branded, brand = "BGP" }: EmailPreviewProps) {
  const base = branded ? wrapInBrandPreview(html, brand) : html;
  // Inject link interceptor before </body> or at the end
  const srcDoc = base.includes('</body>')
    ? base.replace('</body>', LINK_INTERCEPT_SCRIPT + '</body>')
    : base + LINK_INTERCEPT_SCRIPT;

  return (
    <iframe
      srcDoc={srcDoc}
      sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox"
      className={clsx(
        "w-full border border-gray-200 rounded-xl bg-white",
        className
      )}
      title="Email Preview"
      style={{ minHeight: 400 }}
    />
  );
}
