import { Resend } from 'resend';
import prisma from '../lib/prisma';
import { createUnsubToken } from '../routes/email-tracking';
import { wrapInBrandTemplate } from './emailTemplate';
import { rewriteCalendlyLinksInHtml, EMAIL_CAMPAIGN_UTMS } from '../utils/calendlyLinks';
import { sanitizeGreetingName } from '../utils/nameSanitizer';

function personalizeContent(s: string, firstName: string, fullName: string): string {
  return s
    .replace(/\*\|PRIMEIRO_NOME\|\*/g, firstName)
    .replace(/\{\{primeiro_nome\}\}/gi, firstName)
    .replace(/\{\{nome\}\}/gi, fullName);
}

const resend = new Resend(process.env.RESEND_API_KEY);

const TRACKING_BASE_URL = process.env.API_URL || 'http://localhost:3001/api';
const BATCH_SIZE = 10;
const BATCH_DELAY_MS = 1000;

/**
 * Strips the outer document wrapper generated by compileFullHtml() so we get
 * just the inner body content. wrapInBrandTemplate() will re-add the full
 * BGP-branded wrapper, avoiding the "card inside card" double-wrapping issue.
 *
 * Removes: <!DOCTYPE>, <html>, <head>…</head>, <body …>, </body>, </html>,
 * and the outer layout tables (background + content wrapper).
 */
export function stripOuterWrapper(html: string): string {
  let s = html;

  // Remove doctype, html, head, body tags
  s = s.replace(/<!DOCTYPE[^>]*>/gi, '');
  s = s.replace(/<\/?html[^>]*>/gi, '');
  s = s.replace(/<head[\s\S]*?<\/head>/gi, '');
  s = s.replace(/<\/?body[^>]*>/gi, '');

  // Remove the outer centering table (background table → centered table → inner td)
  // Pattern: <table …background-color…><tr><td align="center"…><table …width="6xx"…><tr><td …> CONTENT </td></tr></table></td></tr></table>
  const outerTableRe =
    /^\s*<table[^>]*>\s*<tr>\s*<td[^>]*align=["']center["'][^>]*>\s*<table[^>]*>\s*<tr>\s*<td[^>]*>([\s\S]*)<\/td>\s*<\/tr>\s*<\/table>\s*<\/td>\s*<\/tr>\s*<\/table>\s*$/i;
  const match = s.match(outerTableRe);
  if (match) {
    s = match[1];
  }

  return s.trim();
}

// ── TIME BGP: always receive a copy of every campaign email ──────────────────
const TIME_BGP_EMAILS = [
  'norbert@bertuzzipatrimonial.com.br',
  'mariavitoria@bertuzzipatrimonial.com.br',
  'melissa@bertuzzipatrimonial.com.br',
  'eduardo@bertuzzipatrimonial.com.br',
  'otavio@bertuzzipatrimonial.com.br',
  'thomas@bertuzzipatrimonial.com.br',
  'caio@bertuzzipatrimonial.com.br',
  'henrique.kovalezyk@bertuzzipatrimonial.com.br',
  'gustavo@bertuzzipatrimonial.com.br',
  'joao.lopes@bertuzzipatrimonial.com.br',
  'josi@bertuzzipatrimonial.com.br',
  'joao.rosa@bertuzzipatrimonial.com.br',
  'pedro.arenhaldt@bertuzzipatrimonial.com.br',
  'vicenza.porto@bertuzzipatrimonial.com.br',
  'vitor@bertuzzipatrimonial.com.br',
  'oliver@bertuzzipatrimonial.com.br',
];

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Appends a 1x1 tracking pixel before </body> (or at the end of the HTML).
 */
export function injectTrackingPixel(html: string, sendId: string): string {
  const pixel = `<img src="${TRACKING_BASE_URL}/t/open/${sendId}" width="1" height="1" style="display:none" alt="" />`;

  if (html.includes('</body>')) {
    return html.replace('</body>', `${pixel}</body>`);
  }

  return html + pixel;
}

/**
 * Finds all href="..." in the HTML, replaces each with a tracking redirect URL,
 * and returns the modified HTML along with the list of unique links found.
 */
export function wrapLinksWithTracking(
  html: string,
  campaignId: string
): { html: string; links: { originalUrl: string; trackingId: string }[] } {
  const links: { originalUrl: string; trackingId: string }[] = [];
  const seenUrls = new Map<string, string>();

  const modifiedHtml = html.replace(/href="(https?:\/\/[^"]+)"/gi, (_match, url: string) => {
    // Skip unsubscribe links — they already have their own tracking
    if (url.includes('/unsubscribe/')) {
      return `href="${url}"`;
    }

    let trackingId = seenUrls.get(url);
    if (!trackingId) {
      // Generate a simple unique id (will be replaced by DB cuid on insert)
      trackingId = `${campaignId}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
      seenUrls.set(url, trackingId);
      links.push({ originalUrl: url, trackingId });
    }

    return `href="${TRACKING_BASE_URL}/t/click/${trackingId}"`;
  });

  return { html: modifiedHtml, links };
}

// ─── Main Functions ─────────────────────────────────────────────────────────

/**
 * Sends all queued emails for a campaign, processing in batches to respect
 * Resend rate limits. Creates EmailLink records, injects tracking pixel,
 * wraps links, and updates statuses.
 */
interface SendOptions {
  sendTeamCopy?: boolean;
}

export async function sendCampaignEmails(campaignId: string, options?: SendOptions): Promise<void> {
  const campaign = await prisma.emailCampaign.findUniqueOrThrow({
    where: { id: campaignId },
    include: {
      template: true,
      sends: {
        where: { status: 'QUEUED' },
        include: { contact: true },
      },
    },
  });

  if (!campaign.template) {
    throw new Error(`Campaign ${campaignId} has no template assigned`);
  }

  // Strip the outer wrapper from compileFullHtml() to avoid double-wrapping
  // when wrapInBrandTemplate() adds the BGP branded shell later.
  const baseHtml = stripOuterWrapper(campaign.template.htmlContent);

  // ── Anti-spam: filter out unsubscribed, bounced, and invalid contacts ──
  const contactEmails = campaign.sends.map(s => s.contact.email).filter(Boolean) as string[];
  const suppressedEmails = new Set<string>();

  // Check UnsubscribeList
  if (contactEmails.length > 0) {
    const unsubs = await prisma.unsubscribeList.findMany({
      where: { email: { in: contactEmails, mode: 'insensitive' } },
      select: { email: true },
    });
    unsubs.forEach(u => suppressedEmails.add(u.email.toLowerCase()));
  }

  // Check previously bounced sends (hard bounces)
  if (contactEmails.length > 0) {
    const bounced = await prisma.emailSend.findMany({
      where: { contact: { email: { in: contactEmails, mode: 'insensitive' } }, status: 'BOUNCED' },
      select: { contact: { select: { email: true } } },
      distinct: ['contactId'],
    });
    bounced.forEach(b => { if (b.contact.email) suppressedEmails.add(b.contact.email.toLowerCase()); });
  }

  // Check spam complaints
  if (contactEmails.length > 0) {
    const spam = await prisma.emailSend.findMany({
      where: { contact: { email: { in: contactEmails, mode: 'insensitive' } }, status: 'SPAM' },
      select: { contact: { select: { email: true } } },
      distinct: ['contactId'],
    });
    spam.forEach(s => { if (s.contact.email) suppressedEmails.add(s.contact.email.toLowerCase()); });
  }

  if (suppressedEmails.size > 0) {
    console.log(`[emailSender] Suppressing ${suppressedEmails.size} contacts (unsubscribed/bounced/spam)`);
    // Mark suppressed sends as cancelled
    for (const send of campaign.sends) {
      if (send.contact.email && suppressedEmails.has(send.contact.email.toLowerCase())) {
        await prisma.emailSend.update({
          where: { id: send.id },
          data: { status: 'UNSUBSCRIBED' },
        });
      }
    }
  }

  const fromAddress = `${campaign.fromName} <${campaign.fromEmail}>`;

  // Tagueia links do Calendly com UTMs para o webhook classificar como CALENDLY_EMAIL
  const calendlyTagged = rewriteCalendlyLinksInHtml(baseHtml, EMAIL_CAMPAIGN_UTMS);

  // Wrap links and create EmailLink records for this campaign
  const { html: linkedHtml, links } = wrapLinksWithTracking(calendlyTagged, campaignId);

  // Persist EmailLink records
  for (const link of links) {
    await prisma.emailLink.upsert({
      where: { trackingId: link.trackingId },
      update: {},
      create: {
        originalUrl: link.originalUrl,
        trackingId: link.trackingId,
        emailCampaignId: campaignId,
      },
    });
  }

  // Only skip TIME BGP members from normal sends when team copy is ON (to avoid duplicates)
  const shouldSendTeamCopy = options?.sendTeamCopy !== false;
  const timeBgpSet = new Set(TIME_BGP_EMAILS.map(e => e.toLowerCase()));

  // Process sends in batches
  const sends = campaign.sends.filter(s =>
    s.contact.email
    && !suppressedEmails.has(s.contact.email.toLowerCase())
    && !(shouldSendTeamCopy && timeBgpSet.has(s.contact.email.toLowerCase()))
  );

  for (let i = 0; i < sends.length; i += BATCH_SIZE) {
    const batch = sends.slice(i, i + BATCH_SIZE);

    await Promise.all(
      batch.map(async (send) => {
        try {
          if (!send.contact.email) {
            console.warn(`Skipping send ${send.id}: contact has no email`);
            return;
          }

          // Generate unsubscribe URL for this send
          const unsubToken = createUnsubToken(send.id);
          const unsubUrl = `${TRACKING_BASE_URL}/unsubscribe/${unsubToken}`;

          // Personalização por contato (Mailchimp *|PRIMEIRO_NOME|* + {{nome}}/{{primeiro_nome}}).
          // Nome ofensivo/inválido vira string vazia pra não sair "Olá, <palavrão>".
          const nameGuard = sanitizeGreetingName(send.contact.name);
          const firstName = nameGuard.safe;
          const fullName = nameGuard.flagged ? '' : (send.contact.name || '');

          // Wrap in brand template with unsubscribe link, then inject tracking pixel
          const brandedHtml = wrapInBrandTemplate(linkedHtml, unsubUrl);
          const personalizedHtml = personalizeContent(brandedHtml, firstName, fullName);
          const finalHtml = injectTrackingPixel(personalizedHtml, send.id);
          const personalizedSubject = personalizeContent(campaign.subject, firstName, fullName);

          // Generate plain text from HTML (strip tags)
          const plainText = finalHtml
            .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
            .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
            .replace(/<br\s*\/?>/gi, '\n')
            .replace(/<\/p>/gi, '\n\n')
            .replace(/<\/div>/gi, '\n')
            .replace(/<\/tr>/gi, '\n')
            .replace(/<\/li>/gi, '\n')
            .replace(/<[^>]+>/g, '')
            .replace(/&nbsp;/g, ' ')
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/\n{3,}/g, '\n\n')
            .trim();

          const result = await resend.emails.send({
            from: fromAddress,
            to: send.contact.email,
            replyTo: 'vitor@bertuzzipatrimonial.com.br',
            subject: personalizedSubject,
            html: finalHtml,
            text: plainText,
            headers: {
              'List-Unsubscribe': `<${unsubUrl}>`,
              'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
            },
          });

          // Resend SDK v6+ returns { data: { id }, error } — but sometimes data is null
          const messageId = result.data?.id || (result as any).id || null;
          if (!messageId) {
            console.warn(`[emailSender] Send ${send.id}: Resend returned no messageId`, JSON.stringify(result).slice(0, 200));
          }

          await prisma.emailSend.update({
            where: { id: send.id },
            data: {
              status: 'SENT',
              sentAt: new Date(),
              messageId,
            },
          });
        } catch (error: any) {
          const errorMsg = error?.message || String(error);
          console.error(`Failed to send email for send ${send.id}:`, errorMsg);

          // Only mark as BOUNCED if it's a recipient issue, otherwise mark as FAILED
          const isBounce = errorMsg.includes('bounce') || errorMsg.includes('invalid') || errorMsg.includes('not found');
          await prisma.emailSend.update({
            where: { id: send.id },
            data: { status: isBounce ? 'BOUNCED' : 'QUEUED' }, // QUEUED = can retry later
          });
        }
      })
    );

    // Small delay between batches to respect rate limits
    if (i + BATCH_SIZE < sends.length) {
      await new Promise((resolve) => setTimeout(resolve, BATCH_DELAY_MS));
    }
  }

  // ── Send copy to TIME BGP (BCC-like, one email with all team members) ─────
  if (shouldSendTeamCopy) {
    try {
      const teamHtml = wrapInBrandTemplate(
        `<p style="margin:0 0 12px;font-size:12px;color:#999;background:#f5f5f5;padding:8px 12px;border-radius:4px;">📋 Cópia interna — Campanha: <strong>${campaign.name}</strong> (${sends.length} destinatários)</p>${linkedHtml}`
      );
      await resend.emails.send({
        from: fromAddress,
        to: TIME_BGP_EMAILS,
        replyTo: 'vitor@bertuzzipatrimonial.com.br',
        subject: `[TIME] ${campaign.subject}`,
        html: teamHtml,
      });
      console.log(`[emailSender] Cópia enviada para TIME BGP (${TIME_BGP_EMAILS.length} membros)`);
    } catch (teamErr) {
      console.error('[emailSender] Falha ao enviar cópia pro TIME BGP:', teamErr);
    }
  } else {
    console.log(`[emailSender] Cópia para TIME BGP desativada pelo remetente`);
  }

  // Update campaign status
  await prisma.emailCampaign.update({
    where: { id: campaignId },
    data: {
      status: 'SENT',
      sentAt: new Date(),
      totalRecipients: sends.length,
    },
  });
}

/**
 * Sends a single test email for a campaign without creating EmailSend records.
 */
export async function sendTestEmail(campaignId: string, email: string): Promise<void> {
  const campaign = await prisma.emailCampaign.findUniqueOrThrow({
    where: { id: campaignId },
    include: { template: true },
  });

  if (!campaign.template) {
    throw new Error(`Campaign ${campaignId} has no template assigned`);
  }

  const fromAddress = `${campaign.fromName} <${campaign.fromEmail}>`;

  // Wrap in the same brand template used for real sends so the test is faithful
  const brandedHtml = wrapInBrandTemplate(
    stripOuterWrapper(campaign.template.htmlContent),
  );

  // Tagueia Calendly com UTMs (igual ao envio real)
  const finalHtml = rewriteCalendlyLinksInHtml(brandedHtml, EMAIL_CAMPAIGN_UTMS);

  await resend.emails.send({
    from: fromAddress,
    to: email,
    replyTo: 'vitor@bertuzzipatrimonial.com.br',
    subject: `[TESTE] ${campaign.subject}`,
    html: finalHtml,
  });
}
